project:
  type: website

website:
  favicon: assets/favicon.ico
  google-analytics: G-CES9J82GLL
  page-footer: 
    center:
      - text: About
        href: about.qmd
      - text: License
        href: license.qmd
      - text: GitHub
        href: "https://berkeleymrc.github.io"
    background: "dark"
  sidebar:
    style: "docked"
    title: "INTEGBI 198 <br><small>Fall 2025</small>"
    logo: assets/bmrc_bear.png
    logo-alt: "BMRC logo"
    tools:
      - icon: github
        href: https://berkeleymrc.github.io/fall-2025/
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: syllabus.qmd
        text: Syllabus
      - href: staff.qmd
        text: Staff
      - section: "Other"
        contents:
          - href: faqs.qmd
            text: FAQs
          - href: license.qmd
            text: License

format:
  html:
    theme: lumen
    fontsize: 1em
    css: assets/styles.css
    toc: true
    include-in-header:
      file: siteimprove.html


