---
title: "Frequently Asked Questions"
---

__I am not currently an EMT, can I still enroll in the course?__ <br>
No, Emergency Medicine in Practice is only open to enrollment by BMRC members, who are required to be Nationally Registered Emergency Medical Technicians and hold California State licensure (grey card). Non EMTs are still welcome and encouraged to join us at from 7-8pm on Mondays and Tuesdays to watch presentations and learn more about what being an EMT and a BMRC member is like. More information about these presentations is available on the BMRC instagram ([@mrcberkeley](https://www.instagram.com/mrcberkeley/)).

<br>

__Will attendance be enforced?__ <br>
Attending class and section contributes to achieving the learning outcomes of this course. You should attend every class and section to the best of your abilities, but I understand that extenuating circumstances arise. If you cannot attend a class or section, please stay on track with the covered materials.

On a side note, here's one fun fact from the students' course evaluations. The most common answer provided by the students when asked "What advice would you give to another student who is considering taking this course?" is: __"Go to all the lectures and start working on assignments early."__

<br>

__Will there be live webcast or recordings of lectures?__ <br> (No)
Unless Campus authorities decide to switch to remote instruction, there won't be live webcast or live zoom recordings. With that said, lectures may be recorded for archival purposes, but not necessarily be shared with the class.

<br>

__Do you have a Covid (or other illness) policy?__ <br>
Maintaining your health and that of the Berkeley community is of primary importance to course staff, so if you are feeling ill or have been exposed to illness, please do not come to class. All of the materials used in class will be posted either in this website or in bCourses. Likewise, you’re encouraged to reach out to fellow students to discuss the class materials or stop by office hours to chat with the GSI, the tutor, or the instructor.

Having said that, we expect you to attend lecture and lab. Past experience tells us that students who constantly miss lecture/lab tend to have a mediocre performance.

Also, missing lecture/lab does not give you the right to use OH as a replacement for receiving instruction. We are always willing to help you understand the learning materials during OH, but this also requires that you make an honest effort reviewing them before coming to OH.

<br>

__Are time conflicts allowed?__ <br>
No, if you will be consistently missing a portion of training due to another class, you should not enroll.

<br>
